### PR TITLE
Added export to filesystem option

### PR DESCRIPTION
**Pull request by brendanheywood**
hi @timhunt here is the cleaned up branch from the other closed PR. It now has much better path validation and properly handles the empty data set case.

### CODE REVIEW

**Comment by timhunt** [comment]
Thanks. I finally got around to reviewing this and merging. I am sorry it took so long.

**Comment by timhunt** [comment]
Did you actually tests this code before sending the pull request? The form validation code is generating notices, and prevents you from saving a non-scheduled query.

All you had to do to detect that was to run the Behat tests :-(

I am fixing this now.

**Comment by timhunt** [comment]
OK. Fix done.

**Comment by brendanheywood** [comment]
Sorry for the slip up Tim, can I suggest you setup the travis integration with this github repo. We've been setting up our plugins to use it over the last 6 months and it integrates right into the pull requests and warns when merging etc. We love it, it's awesome! :)

**Comment by timhunt** [comment]
It is awesome, but when you have 30+ plugins you are responsible for, it takes time to set it up for all of them.

**Pull request merged**
