### PR TITLE
CustomSQL - Now displays list of reports in a table format.

### PR DESCRIPTION
**Pull request by michael-milette**
Signed-off-by: Michael Milette <michael.milete@instruxmedia.com>

### CODE REVIEW

**Comment by michael-milette** [comment]
This patch makes it it easier to read the list of reports. Here are a couple of screenshots to demonstrate the difference:

------- Before modification:

image

------- After modification:

image

**Comment by timhunt** [comment]
I just tried to send you this message by email, but your spam fiter rejected it:

Hi,

Clearly you are making a whole bunch of changes to the custom SQL report. Would you like to discuss them before you do lots of work on code that may or may not fit with the way we at the OU see this plugin evolving?

You could post a summary of your proposed changes in the Moodle forum https://moodle.org/mod/forum/view.php?id=44 (a bit like I did for some quiz changes here https://moodle.org/mod/forum/discuss.php?d=231180).

Or, we could have a Skype call or Google hang-out.

**Comment by michael-milette** [comment]
Hi Tim,

Thank you for taking the time to share your thoughts regarding these changes. FYI, I am done making changes for now.

These changes were actually request by one of our client who has kindly agreed to share these back with you and the Moodle community hopes that they be integrated into your core code for the benefit others in the spirit of open source.

If you would rather not included these changes in future releases of your branch, I assure you that we will not be offended and will simply maintain these modifications in our own fork. I can tell you that our clients appreciate the changes and we hope your team at OU will recognize the spirit in which we share these changes with you.

I would be happy to have a chat with you. I have sent you my contact information through the messaging system on Moodle.org.

As for the spam filter, I am not sure what the problem might be. I will look into it. Thanks for letting me know.

Best regards,

Michael

**Comment by timhunt** [comment]
It may not have been spam filter, the bounce was quite cryptic. I was trying to email michael.milete@instruxmedia.com from above.

I am crazily busy at the moment. I have not had time to think if these changes are good or bad. I will try to make time soon, but I have just failed to do that this evening.

**Comment by timhunt** [comment]
I should add, really great in principle that your clients are willing to share these improvements back with everyone. :-)

**Comment by michael-milette** [comment]
No worries Tim, I know how it can be. Don't  stress. Whenever you have time. Looking forward to hearing back from you in the near future.

Cheers,

Michael

**Comment by michael-milette** [comment]
As for the email address, I have to wonder how many fixes I have submitted in the past with the typo in the email address. (make it a double t in my last name). Sorry for the confusion.

**Comment by timhunt** [comment]
Having discussed this at the OU, we don't think this change is an improvement, so I am afraid we won't merge it into the official version. Sorry.

**Pull request closed without merging**
