### PR TITLE
change hardcoded max records to an admin setting

### PR DESCRIPTION
**Pull request by nstefanski**
Added a new setting "max_records" in setting.php.

Removed references to "REPORT_CUSTOMSQL_MAX_RECORDS" in locallib.php and edit_form.php, instead calling plugin config and throwing an error if not set.

Added language strings for config setting and error.

### CODE REVIEW

**Comment by nstefanski** [comment]
I was trying to solve issue #30 by adding a setting page, but keep running into the "Duplicate admin page name" error in Travis CI. Any setting page is getting pulled into the admin tree under both "Reports" and "Plugins -> Reports", and the workaround of creating a new custom tree just causes a new issue of creating the page in both "Plugins -> Reports" and "Plugins -> Custom".

image

I'm not aware of any Report plugins that have a settings page to use as an example. I can't think of a way to avoid the build error other than changing the plugin to a Local plugin with an admin external page under the reports setting, but that's a much bigger change. @timhunt any ideas?

**Comment by timhunt** [comment]
This is not a bad idea, but it needs to be implemented cleanly:
* No need for the exception throws. Moodle ugprade system will ensure that all configs are set.
* The code generally needs to be cleaned up, and we need a single clear commit.

Please resubmit if you are able to re-work this.

**Comment by adpe** [comment]
Hello @timhunt 

Why did you close this issue? I'm also interested to set the hard coded limit to a higher value.

Greets,
Adrian

**Comment by timhunt** [comment]
I did not close the issue. I closed the pull request, for the reasons I stated (briefly) in the comment above.

A pull request is someone suggesting specific changes to the code, to achieve a desired change.

The change people desire is a good idea. The code that tried to implement the idea was not yet good enoguh to be accepted.

If you want to move this forwards, work on improving the code.

**Comment by adpe** [comment]
Sorry! I didn't see that this is the PR.

**Pull request closed without merging**
